version: '3.4'

services:
  bradjolicoeur.web:
    image: bradjolicoeurweb
    container_name: "myapp"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - mynetwork
  proxy:
     build:
      context: .
      dockerfile: Dockerfile-proxy
     container_name: "nginxcore"
     ports:
       - "8080:80"
     networks:
       - mynetwork
     links:
       - bradjolicoeur.web
networks:
  mynetwork:
    driver: bridge