version: '3.4'

services:
  bradjolicoeur.web:
    container_name: "bradjolicoeurweb"
    networks:
      - jolicoeur_net
    build:
      context: .
      dockerfile: Dockerfile
  proxy:
     build:
      context: .
      dockerfile: Dockerfile-proxy
     container_name: "nginxcore"
     networks:
      - jolicoeur_net
     ports:
       - "80:80"
     links:
       - bradjolicoeur.web
networks:
  jolicoeur_net: