version: '3.4'

services:
  website:
    container_name: "website"
    networks:
      - jolicoeur_net
    image: bradjolicoeur/website:latest
  proxy:
     image: nginx:latest
     container_name: "proxy"
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     networks:
      - jolicoeur_net
     ports:
       - "80:80"
     links:
       - website
networks:
  jolicoeur_net: