version: '3.4'

services:
  website:
    container_name: "bjwebsite"
    image: bradjolicoeur/website
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment: 
      ASPNETCORE_URLS: http://*:8484
      SquidexClientId: brad-jolicoeur-blog:read-only-website
      SquidexClientSecret: 93lxzzmqgxvwqkqjaxsha9od0vm3dsuh2zovsa4sqccx
    ports: 
      - "8484:8484"
