version: '3.4'

services:
  website:
    container_name: "website"
    networks:
      - jolicoeur_net
    build:
      context: ../
      dockerfile: ./local-config/Dockerfile
  proxy:
     image: nginx:latest
     container_name: "proxy"
     volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf
       
     networks:
      - jolicoeur_net
     ports:
       - "80:80"
     links:
       - website
networks:
  jolicoeur_net: