// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace bradjolicoeur.Core.Models.ContentType
{
    public partial class CodeSnip
    {
        public const string Codename = "code_snip";
        public const string CodeCodename = "code";
        public const string SyntaxCodename = "syntax";
        public const string DescriptionCodename = "description";

        public string Code { get; set; }
        public IEnumerable<MultipleChoiceOption> Syntax { get; set; }
        public string Description { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}