// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace bradjolicoeur.Core.Models.ContentType
{
    public partial class MarkDownContent
    {
        public const string Codename = "mark_down_content";
        public const string BodyCodename = "body";

        public string Body { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}