// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace bradjolicoeur.Core.Models.ContentType
{
    public partial class Profile
    {
        public const string Codename = "profile";
        public const string NameCodename = "name";
        public const string DescriptionCodename = "description";
        public const string ImageCodename = "image";
        public const string RouteCodename = "route";
        public const string BioCodename = "bio";

        public string Name { get; set; }
        public string Description { get; set; }
        public IEnumerable<Asset> Image { get; set; }
        public string Route { get; set; }
        public IRichTextContent Bio { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}