// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace bradjolicoeur.Core.Models.ContentType
{
    public partial class RichImage
    {
        public const string Codename = "rich_image";
        public const string ImagesCodename = "images";
        public const string DescriptionCodename = "description";
        public const string ContentCodename = "content";
        public const string LabelCodename = "label";

        public IEnumerable<Asset> Images { get; set; }
        public string Description { get; set; }
        public IRichTextContent Content { get; set; }
        public string Label { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}