// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace bradjolicoeur.Core.Models.ContentType
{
    public partial class UrlRedirect
    {
        public const string Codename = "url_redirect";
        public const string RedirectToCodename = "redirect_to";
        public const string RedirectFromCodename = "redirect_from";

        public string RedirectTo { get; set; }
        public string RedirectFrom { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}