name: Deploy to Cloud Run

env:
  PROJECT_ID: bradjolicoeur-web
  ARTIFACT_REGISTRY_REGION: us-east1
  ARTIFACT_REGISTRY_REPO: bj-web
  DOCKER_IMAGE_URL: us-east1-docker.pkg.dev/bradjolicoeur-web/bj-web/bj-web

on:
  push:
    branches:
      - master
      - feature/*
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.ARTIFACT_REGISTRY_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image to Artifact Registry
        working-directory: .
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }} .
          docker push ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }}

  deploy-test:
    runs-on: ubuntu-latest
    environment: 'test'
    needs: build-and-publish
    steps:
      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Test Service
        run: |
          gcloud run deploy bj-web-test \
            --image ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }} \
            --platform managed \
            --region ${{ env.ARTIFACT_REGISTRY_REGION }} \
            --allow-unauthenticated

  deploy-production:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    environment: 'production'
    needs: [build-and-publish, deploy-test]

    steps:
      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Production Service
        run: |
          gcloud run deploy bj-web \
            --image ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }} \
            --platform managed \
            --region ${{ env.ARTIFACT_REGISTRY_REGION }} \
            --allow-unauthenticated
