name: Deploy to Cloud Run

env:
  PROJECT_ID: bradjolicoeur-web
  DOCKER_IMAGE_URL: us.gcr.io/bradjolicoeur-web/bj-web

on:
  push:
    branches:
      - master
      - feature/*
  workflow_dispatch:

jobs:
  deploy-test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker us.gcr.io

      - name: Build and Push Docker Image
        working-directory: .
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }} .
          docker push ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }}

      - name: Deploy to Test Service
        run: |
          gcloud run deploy bj-web-test \
            --image ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }} \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated

  deploy-production:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Production Service
        run: |
          gcloud run deploy bj-web \
            --image ${{ env.DOCKER_IMAGE_URL }}:${{ github.run_number }} \
            --platform managed \
            --region us-east1 \
            --allow-unauthenticated
